<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use PainelDLX\ConfPag\Domain\Entities\GatewayAmbiente;
use PainelDLX\ConfPag\Domain\Entities\GatewayPagamento;
use PainelDLX\ConfPag\Domain\Entities\GatewayPagamentoConfiguracao;
use Vilex\VileX;

/** @var VileX $this */

/** @var GatewayPagamento $gateway_pagamento */
$gateway_pagamento = $this->getAtributo('gateway-pagamento');

/** @var GatewayPagamentoConfiguracao $sandbox */
$sandbox = $gateway_pagamento->getConfiguracaoAmbiente(GatewayAmbiente::SANDBOX);

/** @var GatewayPagamentoConfiguracao $producao */
$producao = $gateway_pagamento->getConfiguracaoAmbiente(GatewayAmbiente::PRODUCAO);
?>

[CORPO]
<h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

<div class="detalhe-gateway-pagamento">
    <details class="detalhe-registro --geral" open>
        <summary class="detalhe-registro-titulo">Geral</summary>

        <p class="detalhe-registro-paragr">
            <span class="detalhe-registro-rotulo">Nome</span>
            <?php echo $gateway_pagamento->getNome() ?>
        </p>

        <p class="detalhe-registro-paragr">
            <span class="detalhe-registro-rotulo">Serviço</span>
            <?php echo $gateway_pagamento->getNomeServico() ?>
        </p>

        <p class="detalhe-registro-paragr">
            <span class="detalhe-registro-rotulo">Usuário Vinculado</span>

            <?php if (!is_null($gateway_pagamento->getUsuario())) :
                echo $gateway_pagamento->getUsuario() ?>
                <a href="javascript:" class="link-editar" onclick="popupVincularUsuario(<?php echo $gateway_pagamento->getId() ?>)" title="Alterar o usuário vinculado a esse gateway de pagamento">
                    Alterar usuário vinculado
                </a>
            <?php else : ?>
                Nenhum usuário vinculado
                <a href="javascript:" class="link-inserir" onclick="popupVincularUsuario(<?php echo $gateway_pagamento->getId() ?>)">
                    Vincular usuário
                </a>
            <?php endif; ?>
        </p>

        <p class="detalhe-registro-paragr">
            <span class="detalhe-registro-rotulo">Ativo?</span>
            <?php echo $gateway_pagamento->isAtivo() ? 'Sim' : 'Não' ?>
        </p>
    </details>

    <details class="detalhe-registro --sandbox" open>
        <summary class="detalhe-registro-titulo">Ambiente de Teste (Sandbox)</summary>

        <?php if (!is_null($sandbox)) : ?>
            <p class="detalhe-registro-paragr">
                <span class="detalhe-registro-rotulo">Usuário / Afiliação</span>
                <?php echo $sandbox->getUsuario() ?>
            </p>

            <p class="detalhe-registro-paragr">
                <span class="detalhe-registro-rotulo">Senha / Token</span>
                <?php echo $sandbox->getSenha() ?>
            </p>
        <?php else: ?>
            <p class="sem-registros">Ambiente de <b>teste</b> não configurado!</p>
        <?php endif; ?>

        <a href="javascript:" onclick="popupConfigAmbiente('sandbox', <?php echo $gateway_pagamento->getId() ?>)" class="botao-salvar" title="Editar configurações de teste">
            Editar configurações
        </a>
    </details>

    <details class="detalhe-registro --producao" open>
        <summary class="detalhe-registro-titulo">Ambiente de Produção</summary>

        <?php if (!is_null($producao)) : ?>
            <p class="detalhe-registro-paragr">
                <span class="detalhe-registro-rotulo">Usuário / Afiliação</span>
                <?php echo $producao->getUsuario() ?>
            </p>

            <p class="detalhe-registro-paragr">
                <span class="detalhe-registro-rotulo">Senha / Token</span>
                <?php echo $producao->getSenha() ?>
            </p>
        <?php else: ?>
            <p class="sem-registros">Ambiente de <b>produção</b> não configurado!</p>
        <?php endif; ?>

        <a href="javascript:" onclick="popupConfigAmbiente('producao', <?php echo $gateway_pagamento->getId() ?>)" class="botao-salvar" title="Editar configurações de produção">
            Editar configurações
        </a>
    </details>
</div>

<div id="popup-config-ambiente" class="popup-modal" style="display: none;"></div>
<div id="popup-vincular-usuario" class="popup-modal" style="display: none;"></div>
[/CORPO]
