PainelDLX\ConfPag\Domain\Entities\GatewayPagamento:
    type: entity
    table: confpag.GatewayPagamento
    repositoryClass: PainelDLX\ConfPag\Infrastructure\ORM\Doctrine\Repositories\GatewayPagamentoRepository
    id:
        id:
            type: integer
            id: true
            nullable: false
            generator:
                strategy: auto
            column: gateway_pagamento_id
    fields:
        nome:
            type: string
            nullable: false
            length: 100
        ativo:
            type: boolean
            nullable: false
        servico:
            type: string
            nullable: false
            length: 255
        deletado:
            type: boolean
            nullable: false
    oneToMany:
        configuracoes:
            targetEntity: GatewayPagamentoConfiguracao
            mappedBy: gateway
            cascade:
                - persist
            joinColumns:
                gateway_pagamento_id:
                    referencedColumnName: gateway_pagamento_id