version: '3.7'
services:
    confpag.dlx.com.br:
        container_name: br.com.dlx.confpag
        build:
            context: .
        volumes:
            - "/Volumes/Arquivos/Pessoal/dlepera/ProjetosWeb/painel-dlx/confpag-dlx/:/var/www/html/confpag.dlx.com.br"
        ports:
            - "8084:80"
        networks:
            - dlx
            - bd
        restart: always
        environment:
            - PHP_IDE_CONFIG=serverName=confpag.dlx.com.br
            - XDEBUG_CONFIG=remote_host=${DOCKER_IP} remote_port=9000
networks:
    bd:
        external: true
    dlx:
        external: true